// Refresh local Google Fonts subsets after adding Chinese UI copy.
// No runtime font requests; unlisted characters use the system fallback.
import fs from 'node:fs/promises'
import path from 'node:path'
import { EXPERIENCE_COPY } from '../src/data/experienceCopy.js'
import { SITE_COPY } from '../src/data/siteCopy.js'
import { CAMPAIGN_COPY } from '../src/data/campaign.js'

async function sourceText(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  return (
    await Promise.all(
      entries.map((entry) =>
        entry.isDirectory()
          ? sourceText(path.join(dir, entry.name))
          : /\.(jsx?|css)$/.test(entry.name)
            ? fs.readFile(path.join(dir, entry.name), 'utf8')
            : '',
      ),
    )
  ).join('')
}
const source = await sourceText('src')
const characters = [
  ...new Set(
    (source.match(/[\u2e80-\u9fff\uff00-\uffef]/gu) || []).concat(
      [...Array(95)].map((_, i) => String.fromCharCode(32 + i)),
      [...'–—’“”·↗↑↓×©'],
    ),
  ),
]
  .sort()
  .join('')
await fs.mkdir('public/fonts', { recursive: true })
const latin = characters.replace(/[^\x20-\x7e–—’“”·↗↑↓×©]/gu, '')
const opening = JSON.stringify([
  EXPERIENCE_COPY.zh.hero,
  EXPERIENCE_COPY.zh.brand,
  SITE_COPY,
  CAMPAIGN_COPY.zh.noticeLabel,
  CAMPAIGN_COPY.zh.noticeText,
])
const cjk = [...characters].filter((character) => !latin.includes(character))
const subsets = [
  ['latin', latin],
  ['opening', cjk.filter((character) => opening.includes(character)).join('')],
  ['body', cjk.filter((character) => !opening.includes(character)).join('')],
]
const families = [
  ...subsets.map(([suffix, text]) => [
    'Noto Sans TC',
    `noto-sans-tc-${suffix}`,
    text,
    'notosanstc',
  ]),
  ...subsets.map(([suffix, text]) => [
    'Noto Serif TC',
    `noto-serif-tc-${suffix}`,
    text,
    'notoseriftc',
  ]),
  [
    'Cormorant Garamond',
    'cormorant-garamond',
    characters.replace(/[^\x20-\x7e–—’“”·×©]/gu, ''),
    'cormorantgaramond',
  ],
]
let css =
  '/* Generated by scripts/prepare-fonts.mjs. SIL Open Font License; see public/fonts. */\n'
for (const [family, stem, text, directory] of families) {
  const url = new URL('https://fonts.googleapis.com/css2')
  url.searchParams.set('family', `${family}:wght@400..700`)
  url.searchParams.set('text', text)
  url.searchParams.set('display', 'swap')
  const response = await fetch(url, {
    headers: {
      'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    },
  })
  if (!response.ok) throw new Error(`Font CSS: ${response.status}`)
  const remoteCss = await response.text()
  if (!/font-weight:\s*400 700\s*;/.test(remoteCss)) {
    throw new Error(`Expected a genuine 400–700 variable font for ${family}`)
  }
  const fontUrl = remoteCss.match(/url\((https:[^)]+)\)/)?.[1]
  if (!fontUrl) throw new Error(`Missing font URL for ${family}`)
  const font = await fetch(fontUrl)
  if (!font.ok) throw new Error(`Font: ${font.status}`)
  const bytes = Buffer.from(await font.arrayBuffer())
  const extension = bytes.subarray(0, 4).toString() === 'wOF2' ? 'woff2' : 'ttf'
  await fs.writeFile(`public/fonts/${stem}.${extension}`, bytes)
  const range = [...text]
    .map((character) => `U+${character.codePointAt(0).toString(16)}`)
    .join(',')
  // Opening text must settle on the complete bundled subset, even on a cold load.
  const display = 'swap'
  css += `@font-face{font-family:"${family}";font-style:normal;font-weight:400 700;font-display:${display};src:url("/fonts/${stem}.${extension}") format("${extension === 'ttf' ? 'truetype' : 'woff2'}");unicode-range:${range}}\n`
  const license = await fetch(
    `https://raw.githubusercontent.com/google/fonts/main/ofl/${directory}/OFL.txt`,
  )
  if (!license.ok) throw new Error(`License: ${license.status}`)
  await fs.writeFile(`public/fonts/${stem}-OFL.txt`, await license.text())
  console.log(`${stem}: ${bytes.length} bytes`)
}
await fs.writeFile('src/fonts.css', css)
